# Generated by Django 4.2.5 on 2023-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecredentials",
            name="credential_type",
            field=models.CharField(
                choices=[("oauth2", "Oauth2")], default=None, max_length=25
            ),
            preserve_default=False,
        ),
    ]
