# Generated by Django 4.2.5 on 2023-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0002_sourcecredentials_credential_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuth2Redirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redirect_code", models.UUIDField()),
                ("redirect_data", models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name="sourcecredentials",
            name="credential_type",
            field=models.CharField(
                choices=[("None", "None"), ("oauth2", "Oauth2")], max_length=25
            ),
        ),
    ]
