# Generated by Django 4.2.5 on 2023-09-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("integration", "0003_oauth2redirection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataFolders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folder_name", models.CharField(max_length=150)),
                ("folder_reference", models.CharField(max_length=150)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("google_drive", "Google Drive"),
                            ("microsoft_onedrive", "Microsoft Onedrive"),
                            ("confluence", "Confluence"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnowledgeCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_name", models.CharField(max_length=150)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.tenant",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OAuth2Redirection",
        ),
        migrations.AddField(
            model_name="datafolders",
            name="knowledge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="integration.knowledgecluster",
            ),
        ),
    ]
