# Generated by Django 4.2.5 on 2023-10-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0004_datafolders_knowledgecluster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=100)),
                ("source_name", models.CharField(max_length=100)),
                ("readable_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="datafolders",
            name="source_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="integration.sourcetype",
            ),
        ),
        migrations.AlterField(
            model_name="sourcecredentials",
            name="source_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="integration.sourcetype",
            ),
        ),
    ]
