# Generated by Django 4.2.5 on 2023-11-06 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("integration", "0005_sourcetype_alter_datafolders_source_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datafolders",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.tenant",
            ),
            preserve_default=False,
        ),
    ]
